version: '3'
services:
  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    networks:
      - backend-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: wordle
    ports:
      - 5432:5432
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/test:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - backend-network
    # depends_on:
    #   - backend

networks:
  backend-network:
